// =============================================================================
// Core Types for PUGs Balancer
// =============================================================================

// Re-export mode types for convenience
export type { GameMode, ModeConfig, CompositionRule } from "./modeConfig";

/**
 * Player roles in Overwatch
 */
export type Role = "Tank" | "DPS" | "Support";

/**
 * Warning severity levels
 */
export type WarningSeverity = "error" | "warning";

/**
 * Warning types that can be generated by the balancer
 */
export type WarningType =
  | "one_trick_conflict"
  | "archetype_gap"
  | "soft_constraint_ignored"
  | "imbalanced_roles"
  | "insufficient_players"
  | "impossible_composition"
  | "must_play_overflow"
  | "constraints_relaxed"
  | "must_play_ignored"
  | "team_lock_ignored"
  | "role_lock_ignored";

// =============================================================================
// Player Types
// =============================================================================

/**
 * Player as stored (imported from CSV)
 */
export interface Player {
  /** Unique identifier, e.g., "Swoo#11605" */
  battletag: string;

  /** Stadium rank for Tank role, e.g., "Pro 2" or null if not willing */
  tankRank: string | null;

  /** Stadium rank for DPS role */
  dpsRank: string | null;

  /** Stadium rank for Support role */
  supportRank: string | null;

  /** Regular comp rank for Tank role (fallback if no Stadium rank) */
  tankCompRank: string | null;

  /** Regular comp rank for DPS role (fallback if no Stadium rank) */
  dpsCompRank: string | null;

  /** Regular comp rank for Support role (fallback if no Stadium rank) */
  supportCompRank: string | null;

  /** Roles the player is willing to play */
  rolesWilling: Role[];

  /** Ordered preference (first = most preferred) */
  rolePreference: Role[];

  /** Heroes the player plays (1-10) */
  heroPool: string[];

  /** @deprecated Use role-specific one-trick fields instead */
  isOneTrick: boolean;

  /** @deprecated Use role-specific one-trick fields instead */
  oneTrickHero: string | null;

  /** One-trick hero for Tank role (null = not a one-trick for this role) */
  tankOneTrick: string | null;

  /** One-trick hero for DPS role (null = not a one-trick for this role) */
  dpsOneTrick: string | null;

  /** One-trick hero for Support role (null = not a one-trick for this role) */
  supportOneTrick: string | null;

  /** Global fallback rank (regular competitive) if no Stadium or role-specific comp rank */
  regularCompRank: string | null;

  /** Manual SR adjustment (-1000 to +1000) */
  weightModifier: number;

  /** Free text notes for pugmaster reference */
  notes: string | null;

  /** All-time wins by mode */
  stadiumWins: number;
  regular5v5Wins: number;
  regular6v6Wins: number;

  /** @deprecated Use mode-specific wins instead */
  allTimeWins: number;
}

/**
 * Player in context of current session (extends Player with session state)
 */
export interface LobbyPlayer extends Player {
  /** Player sat out last game and must play this game */
  mustPlay: boolean;

  /** Must-play priority (2 = sat out waiting, 1 = joined mid-match, 0 = not must-play) */
  mustPlayPriority: number;

  /** Number of consecutive games this player has sat out (0 = played last game) */
  consecutiveSatOut: number;

  /** Locked to a specific team by pugmaster */
  lockedToTeam: 1 | 2 | null;

  /** Locked to a specific role for this session (player wants to play this role) */
  lockedToRole: Role | null;

  /** Temporary weight override for this session only */
  tempWeightOverride: number | null;

  /** Adaptive weight adjustment based on match scores (separate from manual) */
  adaptiveWeight: number;

  /** Currently AFK/BRB — excluded from balancing */
  isAfk: boolean;

  /** Number of consecutive losses (0 = none, 1+ = on loss streak) */
  consecutiveLosses: number;
}

// =============================================================================
// Team Assignment Types
// =============================================================================

/**
 * A single player's role assignment within a team
 */
export interface RoleAssignment {
  /** The player being assigned */
  player: Player;

  /** The role they are assigned to play */
  assignedRole: Role;

  /** Calculated SR for this player in this role (with modifiers) */
  effectiveSR: number;
}

/**
 * Score breakdown for a team assignment
 */
export interface TeamScore {
  /** Average SR of team 1 */
  team1SR: number;

  /** Average SR of team 2 */
  team2SR: number;

  /** Absolute difference between team SRs */
  srDifference: number;

  /** Whether archetype parity requirements are met */
  archetypeParityMet: boolean;
}

/**
 * Warning generated during balancing
 */
export interface Warning {
  /** Type of warning */
  type: WarningType;

  /** Human-readable message */
  message: string;

  /** Severity level */
  severity: WarningSeverity;
}

/**
 * Complete team assignment output from the balancer
 */
export interface TeamAssignment {
  /** Team 1 role assignments (1 Tank, 2 DPS, 2 Support) */
  team1: RoleAssignment[];

  /** Team 2 role assignments (1 Tank, 2 DPS, 2 Support) */
  team2: RoleAssignment[];

  /** Warnings generated during balancing */
  warnings: Warning[];

  /** Score breakdown for this assignment */
  score: TeamScore;
}

// =============================================================================
// Session State Types
// =============================================================================

/**
 * Soft constraint between two players
 */
export interface SoftConstraint {
  /** Type of constraint */
  type: "together" | "apart";

  /** Battletag pair */
  players: [string, string];
}

/**
 * Session state managed by the application
 */
export interface SessionState {
  /** Battletags of players in current lobby */
  lobbyBattletags: string[];

  /** Battletags of players that MUST play */
  mustPlay: Set<string>;

  /** Battletags locked to team 1 */
  lockedTeam1: Set<string>;

  /** Battletags locked to team 2 */
  lockedTeam2: Set<string>;

  /** Battletags locked to a specific role (battletag -> role) */
  lockedRoles: Map<string, Role>;

  /** Temporary weight overrides (battletag -> modifier) */
  tempWeightOverrides: Map<string, number>;

  /** Currently AFK players */
  afkPlayers: Set<string>;

  /** Soft constraints for this session */
  softConstraints: SoftConstraint[];

  /** Last generated result */
  lastResult: TeamAssignment | null;

  /** Battletags of players who played last game (for sat-out tracking) */
  lastGamePlayers: Set<string>;

  /** Consecutive losses per player (battletag -> count) */
  playerLossStreaks: Map<string, number>;

  /** Consecutive games sat out per player (battletag -> count) */
  satOutStreaks: Map<string, number>;
}

// =============================================================================
// Utility Types
// =============================================================================

/**
 * Result of CSV validation
 */
export interface ValidationResult {
  /** Successfully parsed players */
  valid: Player[];

  /** Errors that prevent import */
  errors: ValidationError[];

  /** Warnings that don't block import */
  warnings: ValidationWarning[];
}

export interface ValidationError {
  /** 1-based row number in CSV */
  row: number;

  /** Field that caused the error */
  field: string;

  /** Error message */
  message: string;
}

export interface ValidationWarning {
  /** 1-based row number in CSV */
  row: number;

  /** Warning message */
  message: string;
}
